[workspace]
members = [
    "rust-coding-guidelines/fork-and-signals",
    "rust-coding-guidelines/fork-variables",
    "rust-coding-guidelines/struct-packing",
    "rust-coding-guidelines/syscalls-example",
]
resolver = "2"
