[project]
name = "llm-book"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.1",
    "pympler>=1.1",
    "scikit-learn>=1.6.1",
    "statsmodels>=0.14.4",
    "tiktoken>=0.9.0",
    "torch>=2.6.0",
]
