.PHONY: main-01
main-01:
	nvcc 01-main.cu -o 01-main.out
	./01-main.out
	nvcc 02-hello.cu -o 02-hello.out
	./02-hello.out
	nvcc 03-cudaDeviceProp.cu -o 03-cudaDeviceProp.out
	./03-cudaDeviceProp.out
	nvcc 04-choose-gpu.cu -o 04-choose-gpu.out
	./04-choose-gpu.out