[hooks]
pre-commit = ["cargo test", "cargo check", "cargo audit", "git-secrets --scan -r"]
pre-push = ["cargo fmt -- --check", "git secrets --scan-history"]
post-commit = "echo yay"

[logging]
verbose = true
